### ISSUE TITLE
Update Question

### ISSUE THREAD

**Issue by Sleepinubbins** [blaxxun-boop/Foraging#10]
Hey sorry to put this here, don't know how to get in contact with you but I was wondering if you were going to update this mod and others like it (sailing, woodcutting, mining, ect) or have you made a pack mod with all of them?

I really love your skill mods and hope to see them again soon (sailing was made SO much more fun with you mod). I hope all is well.

**Comment by blaxxun-boop** [comment]
All of them work.

**Comment by Sleepinubbins** [comment]
Ah ok. For some reason they dont for me. Is there a load order? Do they conflict with Valhiem Plus?

**Comment by blaxxun-boop** [comment]
Read this: https://github.com/blaxxun-boop/PassivePowers/issues/5

**Comment by Sleepinubbins** [comment]
Oh! Ok thank you so much. That sounds like a huge pain. I agree, mod creators shouldnt have to dance around ONE mod pack just because servers use it most.

I appreciate your hard work! I'll be dropping V+ so I can go back to using your awesome mods! Cant wait to see more of your work! Again, thank you for letting me know and dont work too hard!
