### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by Maxphog** [blaxxun-boop/Foraging#7]
mod name: Seasons 1.0.13
mod author: Shudnal
mod link: https://valheim.thunderstore.io/package/shudnal/Seasons/

![302507758-686e282e-406c-4179-aa43-4d2a9f7e07b1](https://github.com/blaxxun-boop/Foraging/assets/113948291/b7818935-7e54-4d9a-b410-2b5177aaecea)

issue: foraging skill effects and buffs that affect amount of drops are picked from ground pickable foods is overwritten by the seasons mod.

replication method:

1. hop on a world with the two mods enabled
2. open dev commands
3. spawn a berry bush
4. raise you foraging skill by like a couple dozens with the command `raiseskill Foraging 24 `
5. pick a berry.

Expected result: should at least get more than 2 or 3 berries from a single berry bush if your foraging skill is higher.

actual result: you actually only receive one berry.

tested with 4 different berry bushes and a Foraging skill level higher than 30.

![302507272-8caf25be-20e0-4142-b075-1cf997e92bc4](https://github.com/blaxxun-boop/Foraging/assets/113948291/1d8a9c87-bb80-4928-b9dd-a9b095b66d94)

![302507687-0737fc4d-0deb-4def-bfcf-6cb018501aaf](https://github.com/blaxxun-boop/Foraging/assets/113948291/be8c90a7-574e-420f-8648-81ce949a0714)

**Comment by Maxphog** [comment]
before installation of the seasons mod the foraging skill was working as intended in the latest version of valheim as of this post.
hows my bug report Smoothbrain ? i hope its good

**Comment by blaxxun-boop** [comment]
Your bug report is with the wrong mod. Report it to the author of the seasons mod.
